{
 "title": "Seatunnel",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(cluster_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "UP Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_state{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hazelcast Partition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "partitionCount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "hazelcast_partition_partitionCount{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "activePartition",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "hazelcast_partition_activePartition{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "isClusterSafe",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "hazelcast_partition_isClusterSafe{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "isLocalMemberSafe",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "hazelcast_partition_isLocalMemberSafe{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hazelcast Executor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "executedCount",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "hazelcast_executor_executedCount{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "isTerminated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "hazelcast_executor_isTerminated{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "isShutdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "hazelcast_executor_isShutdown{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "poolSize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "hazelcast_executor_poolSize{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "maxPoolSize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "hazelcast_executor_maxPoolSize{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "queueRemainingCapacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "hazelcast_executor_queueRemainingCapacity{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "queueSize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "hazelcast_executor_queueSize{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$__interval])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "100 * (jvm_memory_bytes_used{instance=~\"$instance\",area=\"heap\"} / jvm_memory_bytes_max{instance=~\"$instance\",area=\"heap\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count[$__interval])",
     "legendFormat": "{{instance}}-{{gc}}"
    }
   ]
  },
  {
   "title": "GC Cost Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}[$__interval])*1000",
     "legendFormat": "{{instance}}-{{gc}}"
    }
   ]
  },
  {
   "title": "Jvm Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-current"
    },
    {
     "expr": "jvm_threads_daemon{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-daemon"
    },
    {
     "expr": "jvm_threads_peak{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-peak"
    },
    {
     "expr": "jvm_threads_deadlocked{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-deadlocked"
    }
   ]
  },
  {
   "title": "Job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Job Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(job_count) by (type) ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Job Thread Pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "job_thread_pool_activeCount{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{type}}"
    },
    {
     "expr": "job_thread_pool_corePoolSize{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{type}}"
    },
    {
     "expr": "job_thread_pool_poolSize{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "Job Thread Pool Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "job_thread_pool_completedTask_total{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{type}}"
    },
    {
     "expr": "job_thread_pool_task_total{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  }
 ]
}